### ISSUE TITLE
Custom Mapbox Studio layer + Points on map

### ISSUE THREAD

**Issue by machikoyasuda** [maptimeLA/old-la-restaurants#11]
- Use custom mapbox studio layer: https://api.mapbox.com/v4/maptimelaomar.f91a81fd/page.html?access_token=pk.eyJ1IjoibWFwdGltZWxhb21hciIsImEiOiI0OTM4MWMwZDE2ZmU1OWYzMTNhOTkxZGFhMTc3ZWZkZiJ9.bQawylJZhz888XtP7TGBbg#14/34.0612/-118.2719
- Put restaurants on map
- Color the restaurant points by decade
- Clicking on dots gives you basic data on the map

**Comment by machikoyasuda** [comment]
@Miguel-Estrada

**Comment by chanbot5000** [comment]
I added the custom mapbox layer, put the restaurants on the map, and the popup window gives basic info on the data points. I will next add coloring for decades.

**Comment by machikoyasuda** [comment]
:100:

**Comment by MtnBiker** [comment]
Not sure if this is the right place, but probably better than Slack. Anyway, the page now shows correctly in OSX Safari (Version 9.0 (10601.1.56.2)) and in Firefox. 

`OSX Chrome only shows the map without points. Two errors:
Refused to execute script from 'https://raw.githubusercontent.com/calvinmetcalf/leaflet-ajax/master/dist/leaflet.ajax.min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
(index):35 Uncaught TypeError: L.GeoJSON.AJAX is not a function`

All three browsers produce good results when the script is pasted (replacing the src=…)  into the index.html page. 

Adding `type="text/javascript"` makes no difference.

PS. Why does adding `<!DOCTYPE html>` break the page?

**Comment by cityhubla** [comment]
I turned the default blue markers into circlemakers in the `omar_circlemarkers` branch. I also made a function to color style the fills by the decades they were in. 

![capture1](https://cloud.githubusercontent.com/assets/6407796/10527821/708f59e6-7347-11e5-95ab-570c79c9a6e2.PNG)

**Comment by cityhubla** [comment]
It would be cool to make some sort of buttons with decade labels for one to click, once clicked the markers in that decade would animate by expanding and the others with a slight fade

**Comment by MtnBiker** [comment]
Or a slider that brought up the Restos as they opened. Or combined with your idea. 

Greg

**Comment by cityhubla** [comment]
@MtnBiker, slider should be a feature, thoughts on markers? (style, shape, size). I'll create separate issues for feature addons

**Comment by cityhubla** [comment]
It looks like this issue is pretty much resolved as we now are using a custom map with points. Great work everyone!
